// The Netlify origin the web app deploys to. On first launch the app mirrors
// every file listed in `${ORIGIN}/mirror-manifest.json` (generated by the root
// vite.config.ts build) onto the device, then never contacts this origin again.
//
// TODO: replace with the real deployed URL once the site is live, e.g.
// 'https://readback.netlify.app'. During local development you can instead
// point this at `vite preview`'s LAN URL (both devices must be on the same
// network), e.g. 'http://192.168.1.23:4173'.
export const ORIGIN = 'https://REPLACE-WITH-YOUR-NETLIFY-SITE.netlify.app'

// Subfolder of the app's document directory that mirrors ORIGIN's dist/ output.
export const WEBROOT_DIR = 'webroot'

// Bumping this forces a full re-mirror (e.g. after a Kokoro model revision change).
// Keep in sync with the mirror-manifest.json content itself, which is checked first.
export const MIRROR_STATE_FILE = '.mirror-complete'
