// Mirrors the web app's build output (dist/) onto the device once, then never
// touches the network again. `${ORIGIN}/mirror-manifest.json` is generated by the
// root vite.config.ts build: every file in dist/ except the WebGPU-only fp32
// model (mobile WebViews have no WebGPU, so that ~310MB file is never needed here).
import * as FileSystem from 'expo-file-system/legacy'
import { MIRROR_STATE_FILE, ORIGIN, WEBROOT_DIR } from './config'

type Manifest = Record<string, number>

export interface MirrorProgress {
  file: string
  filesDone: number
  filesTotal: number
  bytesDone: number
  bytesTotal: number
}

function webrootDir(): string {
  if (!FileSystem.documentDirectory) throw new Error('No writable document directory on this platform.')
  return `${FileSystem.documentDirectory}${WEBROOT_DIR}/`
}

async function ensureDir(uri: string) {
  const info = await FileSystem.getInfoAsync(uri)
  if (!info.exists) await FileSystem.makeDirectoryAsync(uri, { intermediates: true })
}

async function fileMatches(uri: string, expectedSize: number): Promise<boolean> {
  const info = await FileSystem.getInfoAsync(uri)
  return info.exists && !info.isDirectory && info.size === expectedSize
}

/**
 * Downloads every file in the manifest that isn't already present with the
 * right size, then writes a completion marker. Safe to call on every launch:
 * once the marker matches, this returns almost immediately without touching
 * the network — that's what makes the model "downloaded once."
 */
export async function ensureMirrored(onProgress?: (p: MirrorProgress) => void): Promise<string> {
  const root = webrootDir()
  await ensureDir(root)

  const markerUri = `${root}${MIRROR_STATE_FILE}`
  const manifestRes = await fetch(`${ORIGIN}/mirror-manifest.json`)
  if (!manifestRes.ok) throw new Error(`Could not fetch mirror-manifest.json (HTTP ${manifestRes.status})`)
  const manifest: Manifest = await manifestRes.json()
  const manifestJson = JSON.stringify(manifest)

  const marker = await FileSystem.getInfoAsync(markerUri)
  if (marker.exists) {
    const previous = await FileSystem.readAsStringAsync(markerUri)
    if (previous === manifestJson) return root
  }

  const entries = Object.entries(manifest)
  const bytesTotal = entries.reduce((sum, [, size]) => sum + size, 0)
  let bytesDone = 0

  for (let i = 0; i < entries.length; i++) {
    const [path, size] = entries[i]
    const dest = `${root}${path}`
    if (!(await fileMatches(dest, size))) {
      await ensureDir(dest.slice(0, dest.lastIndexOf('/') + 1))
      const result = await FileSystem.downloadAsync(`${ORIGIN}/${path}`, dest)
      if (result.status !== 200) throw new Error(`Download failed for ${path} (HTTP ${result.status})`)
    }
    bytesDone += size
    onProgress?.({ file: path, filesDone: i + 1, filesTotal: entries.length, bytesDone, bytesTotal })
  }

  // Written last: if the app is killed mid-mirror, the marker is absent (or stale)
  // and the next launch resumes by re-checking every file's size, so a half
  // download never gets mistaken for a complete one.
  await FileSystem.writeAsStringAsync(markerUri, manifestJson)
  return root
}
